### ISSUE TITLE
Any plans to integrate gnome-keyring instead of kde-wallet for saving credentials?

### ISSUE THREAD

**Issue by dhammel** [ProtonVPN/linux-app#45]
I run Kubuntu 21.04, and only use kde wallet for protonvpn as its required.

Any kde related software, such as with entering wifi passwords to connect to wifi, unlocking luks devices... all prompt me to unlock kwallet, which I have to keep cancelling out as I dont want to use it to save those credentials. The only way I know of getting rid of these prompts to unlock kwallet ia disabling the kwallet submodule in system settings, but then protonvpn is unable to retrieve the credentials to login.

If no plans of integrating gome-keyring, is there at least a way of addressing above issue?

Thank you :)

**Comment by calexandru2018** [comment]
Hey @dhammel 

I'm not sure exactly what you mean here. Our client works with both gnome-keyring and kwallet.

**Comment by dhammel** [comment]
@calexandru2018

Now that I re-tried, disabling kdewallet submodule on the latest update, it now does prompt to to unlock gnome-keyring as it's installed. Like it was recently added, thats new for me. However, I'm experiencing an issue.

When kdewallet disabled, I issued command (note - I use pvpn as an alias): pvpn login {email}, then it gives me an output error/warning stating kwallet backend was not found, then entered protonmail password as requested, stated the usual success message, and it was indeed saved into gnome-keyring. Then when issuing pvpn c --f, it gave me the same output error of kwallet backend not found, followed by a bunch of other output and then some prompt appeared telling me to provide the secret to the server US-IL#34 with a Password dialog box (appears like it's a reported dialog from the os itself, part of the loal VPN connections), the protonmail password didn't work but the OpenVPN one did. However, the dialog box as mentioned appears each time i re-connect, as if it's not saving the openvpn password in gnome-keyring like it does with kwallet.

Doesn't seem like protonvpn has any customizability in terms of specifiy which backend to use for credential storage, what to store...which would be useful as well to have.

Since it contains too much verbose data, I have saved it in a txt, attached.
[log.txt](https://github.com/ProtonVPN/linux-app/files/7244560/log.txt)

**Comment by calexandru2018** [comment]
@dhammel I get it, but there are multiple issues, in fact, if you'd contact support they'd explain you. To start, I would like to ask for the ouput of the following for further clarification:

- open gnome-keyring (usually seahorse)
- search for protonvpn entries
- type` pvpn c --f`. During the connection process, take notice if an entry is added to gnome-keyring. It should contain the name of the connection ie: `ProtonVPN PT#12`

**Comment by dhammel** [comment]
@calexandru2018 

No, there is no entry that appears in gnome-keyring when looking through seahorse during the connection.

I dont know what those issues are, may contact support but either way if its not to be address it'll be an issue for me anyway, some other vpn apps dont even use these methods on linux, its more of an invisible process, so Im not sure what methods others are using, but I wouldn't see how this issue couldn't be fixed, unless its some limitation of the programming language being used (python, right?)

**Comment by calexandru2018** [comment]
@dhammel please try the second method and provide me with some feedback

**Comment by dhammel** [comment]
@calexandru2018 

The same thing occurs, continuous prompt for password (needing the openvpn password).

I do see one thing, that may be an issue. On Kubuntu, whenever entering a password for a new wifi connection it automatically prompts kwallet to create a new wallet, or unlock existing one to save credentials, if cancelled (or submodule disabled prior), then upon disconnection/re-connection it will need password for wifi, unless your disable a certain option in the security settings of the wifi's configuration (same option appears in the vpn section, once the ovpn was imported). Default option is: Store password for this user only (encrypted). I never use this option, as its somewhat pointless especially as my disk is encrypted via luks anyway, and my pc never gets compromised, so always have to switch it to: Store password for all users (not encrypted). So during a connection via pvpn cli, would it be attemping to following through with its default option for storing password (trying to use kwallet)? Even if it was though, since the openvpn password is already saved in gnome-keyring, couldn't it pass it through to automate this, or would that need some sort of api, or bridge integrated into the network manager to do?

Of course, since a username was also needed, i had to enter that in the username box, keeping the password box empty. Then during connection, it would keep prompting me each connection attempt for the password to server. If I entered the password in the box prior, it would prompt kwallet to save it, unless it switched it to the (not encrypted) option, which would then save it unecrypted. username appears to be in an always unencrypted state regardless of the usage of kwallet.

**Comment by calexandru2018** [comment]
Great thank you. The reason I wanted you to try it out was so that you could see the results by yourself, so here's a brief explanation of why:

- Distros are configured to run with a set of default applications and services, which are usually dependent on the DE
- Gnome-keyring and KWallet (or Gnome and KDE DEs for that matter) are not exclusive, but the distros software were tuned to work in harmony with each other
- With that said, if you install Kubuntu (which is KDE based) and slap gnome-keyring on it, you're just de-stabilizing your distro. Yes you may not experience major instabilities at first, but I'll give you a brief example with our client:
  - Our client will prioritize the keyring backend based on your DE. In fact, this is done automatically by the [python-keyring](https://github.com/jaraco/keyring) package.
  - Our client will **always** store the password "Only for this user", as this is **one of the** most safest ways to store credentials. Yes we can store for all users, but then if root is compromised then the password would be visible under `/etc/NetworkManager/system-connections/`, while storing in a users keyring, not even root can see the password. But that's a whole discussion in itself (root hijackin).
  - Given the previous two points, we now understand why our client will prefer KWallet over Gnome-keyring.
  - The problem now is, even if we store in the correct backend keyring, NM will still try to fetch from the default DE keyring backend, which is KWallet (which you've experienced yourself). At this point, yes we could let the user choose which keyring backend they prefer, and I agree with that (and it's something that we've discussed in implementing later). But the problem now becomes that NM is misaligned with your current system configurations, which for it to work properly, you need to tweak the settings in your system, so that (in this case) NM correctly fetches the data from Gnome-keyring instead of insisting with KWallet (which btw is not able and thus prompts your for the openvpn password).

Hope this is clear for you.

**Comment by dhammel** [comment]
Well I understand that, and I would prefer to use kwallet as its part of the system but there are 2 drawbacks. First of all, protonmail bridge & import/export app which I use only use integration of gnome-keyring or pass (last I checked anyway) which is only reason I even have gnome-keyring, because I tried pass and couldn't get it to work (be detected by bridge or import export app at all). If either of those apps support kwallet now, or integrate it soon then i could switch all to kwallet.

The 2nd drawback is that, when the kwallet submodule is enabled, as I mentioned in first post (reason for opening this issue), anytime i add/edit password for wifi network, or unlock encrypted luks devices it prompts me to unlock kwallet to save those credentails when I don't want to (the password for those are saved in my password manager, keepass). That gets annoying, and when i asked a question on askubuntu if there was a way to keep kwallet submodule enabled, but instruct the system in some way to not request to save any credentials in kwallet on behalf of any desktop environment related software such as the network manager, but I kept getting answers saying that its not currently possible, it's either all or nothing. Each time i unlock a luks device, having to cancel the prompt to unlock kwallet 2 or 3 times each time is annoying.

One thing to mention is that security should be decided by the user, rather than the developer/company behind it. Of course having secure defaults are a good thing, but options for user to lower security should be up to user (after all, user could decide not to use protonvpn at all, if no option is given, and go to other companies who provide it, some of which do...and they may be worse at security and the user would be unaware). In my case, I know my pc is not compromised. I use security software to ensure that, only install free, trusted & open source software, any security related software other the vpn such as encryption tools like luks, veracrypt & keepass I have self-compiled. I do a lot to make sure my pc is not/will not be compromised in any way, so for me thats not much of a concern.

**Comment by dhammel** [comment]
This is weird, now I tried to switch back to using kwallet. Ran pvpn logout (to remove it from gnome-keyring). Re-enabled the kwallet submodule, ran pvpn login {email}, unlocked kwallet, then entered protonmail password. Now during each connections it still giving me that same prompt to enter secrets to connect to server us-IL#17. It never use to ask this when using kwallet, as Im using again now and this time gave me no ouput of errors in terminal.

**Comment by calexandru2018** [comment]
Hey @dhammel 

You can always use openvpn. And in regards to your original question, we could allow users to use a different backend for keyring but the problem is is not exactly that, but rather expecting NetworkManager to understand your change, without actually tweaking it's configuration.
