### ISSUE TITLE
linux app don't ask for 2FA code when acces with protonmail credentials

### ISSUE THREAD

**Issue by gpdevsoft** [ProtonVPN/linux-app#73]
on *ubuntu 22.04 please can you implement request for 2FA code? your services are very safe but the lack of 2FA even in the desktop version for linux I think it is a serious lack, moreover I always connect with the old OpenVPN protocol and yet the linux kernel in the * ubuntu 22.04 distro natively supports Wireguard.
thank you!

**Comment by ProfessorCode212** [comment]
@gpdevsoft I think it's the same across all platforms, not just Linux. However, I also think it would be nice if the app supported 2FA. :smiley:

**Comment by gpdevsoft** [comment]
@ProfessorCode212 on Android and Windows ask for 2FA

**Comment by calexandru2018** [comment]
Hey @gpdevsoft 

It's actually known that it "bypasses" 2FA although what actually happens is that the session has permission to only connect to the vpn and **can not** make any changes to your account due to the restricted scope (not being authenticates via 2FA). 

Most of the other clients have this already implemented, but it wasn't such the case some months ago.

Lastly, given that we're working on a new Linux client (read more [here](https://github.com/ProtonVPN/linux-cli/issues/64#issuecomment-1058224569), we won't be adding 2FA support on the current client.

**Comment by gpdevsoft** [comment]
Ok, thank you for clarification and good job!
