### ISSUE TITLE
How can I make my wireless printer work?

### ISSUE THREAD

**Issue by pil0u** [ProtonVPN/linux-app#78]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Hi,

I am not sure yet if my issue originates from my local machine or the VPN, that's why I prefer to ask a question first.

My wireless printer works fine under my home connection. When I activate the VPN through the official app, my printer cannot receive printing instructions.
I do have access to my local network under the VPN:
- my router @ 192.168.1.1 is reachable
- my printer @ 192.168.1.72 is reachable (port 80, a web server with HP services)

But printing a page from any app (Firefox, LibreOffice, PDF reader) does not work.

Any idea where this problem can come from?

Thank you,
Pierre-Loïc

**Comment by phrxmd** [comment]
This is hard to say without knowing your printer model and how you configured it, as well as how your firewall and VPN are configured.

The printer seems to be a HP model. It could be that CUPS actually doesn't see it over the VPN because HP uses different protocols (Zeroconf, SLP or mDNS/Bonjour) for printer discovery. Those use multicast and your VPN or firewall may not pass multicast packets. 

Try to remove your printer and run `hp-setup` to see if it can discover your printer. You may need to try with different discovery methods (Avahi/Zeroconf/mDNS or SLP). The former is usually easier, but not the default with `hp-setup`. 

To get it to work, you may need to do some configuration of your VPN or firewall. 

For reference, [here](https://forums.opensuse.org/showthread.php/540663-Firewall-configuration-for-HPLIP-hp-setup-printer-autodiscovery) is what I needed to do to get HP printer discovery to work on OpenSUSE. Note that I don't recommend the SLP method, as it required tinkering quite deeply in the Linux network stack.

**Comment by pil0u** [comment]
Thanks a lot @phrxmd for your detailed answer and your help.

I actually managed to make it work without tweaking much into the terminal of the CUPS stuff.
Setting a static IP for the printer probably didn't help but I think it's a good practice. Then I just wiped out every printer configured on my laptop. Afterwards, I configured the printer while the VPN was active and a printer with a slightly different name appeared. Then everything worked as expected, even with the VPN off.

I might have tweaked things with the network settings on the printer itself, but I can't remember. Also, no firewall involved for my case.

Thanks again for the leads, and I'll be more precise with my setup next time. Take care
